### ISSUE TITLE
User registration failure

### ISSUE THREAD

**Issue by loghanz85** [Tracman-org/Server#82] opened 2017-05-02 18:32 UTC

**Comment by keith24** [comment] 2017-05-03 23:36
Thanks for reporting this!  It is certainly an issue.  

From the logs: 
```
May 03 13:44:38 khp nodejs[16624]: ❌ Error: data and hash arguments rquired
May 03 13:44:38 khp nodejs[16624]:     at /srv/tracman/node_modules/bcrypt/bcrypt.js:179:16
May 03 13:44:38 khp nodejs[16624]:     at _combinedTickCallback (internal/process/next_tick.js:73:7)
May 03 13:44:38 khp nodejs[16624]:     at process._tickCallback (internal/process/next_tick.js:104:9)
```
Definitely an issue from switching the `bcrypt` and `bcrypt-nodejs` packages.  

I've run out of mobile hotspot but I will fix it Friday when I get home.

**Comment by keith24** [comment] 2017-05-06 02:32
I wasn't able to reproduce this... Where exactly did you have a problem?

**Comment by keith24** [comment] 2017-05-23 00:19
Closing because I don't know.

**Closed by keith24** 2017-05-23 00:19 UTC
Labels: auth, backend, bug
